meta_product_name: "Centrum Psychoterapii"
meta_title: "Centrum Psychoterapii 'Psycho-Terapeutyczny' w Koszalinie | Psychoterapia i Pomoc Psychologiczna"
meta_description: "Psycholog | Psychoterapeuta w Koszalinie. Konsultacja psychologiczna, Psychoterapia indywidualna, Terapia małżeńska, Diagnoza i Terapia dzieci, Pomoc w sytuacji kryzysowej, Pomoc w uzależnieniach."
meta_image: "cover.jpg"
